# Generated by Django 3.2.14 on 2022-07-13 20:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('booked_date', models.DateField()),
                ('booked_time', models.TimeField(default=datetime.time(0, 0))),
                ('party_size', models.PositiveSmallIntegerField()),
                ('extra_info', models.TextField(blank=True)),
                ('booked_on', models.DateTimeField(auto_now=True)),
                ('approved', models.BooleanField(default=False)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['booked_date'],
            },
        ),
    ]
